#!/usr/bin/env bash

class=$(hyprctl activewindow -j | jq -r '.class // empty')
fallback="/usr/share/icons/Adwaita/scalable/mimetypes/application-x-executable.svg"

case "$class" in
"dev.zed.Zed") echo "/home/arsh/.local/zed.app/share/icons/hicolor/512x512/apps/zed.png" ;;
"firefox") echo "/usr/share/icons/hicolor/256x256/apps/firefox.png" ;;
"kitty") echo "/usr/share/icons/hicolor/256x256/apps/kitty.png" ;;
"discord" | "vesktop") echo "/usr/share/icons/hicolor/scalable/apps/vesktop.svg" ;;
"equibop") echo "/usr/share/pixmaps/equibop.png" ;;
"Spotify" | "spotify") echo "/usr/share/pixmaps/spotify-client.png" ;;
"code" | "code-url-handler") echo "/usr/share/pixmaps/vscode.png" ;;
*) echo "$fallback" ;;
esac
